%MU_PSQL%
DROP TABLE IF EXISTS User_Gen;
DROP TABLE IF EXISTS User_Loc;
DROP TABLE IF EXISTS User_Device;
DROP TABLE IF EXISTS User_Friends;
DROP TABLE IF EXISTS User_Pers;
DROP TABLE IF EXISTS Groups_Info;
DROP TABLE IF EXISTS User_Groups;
